### Create Client
POST http://localhost:3000/client
Content-Type: application/json

{
    "name": "Don Quixote",
    "email": "LaMachaland@gmail.com",
    "password": "Rocinante3&"
}

### Get All Clients
GET http://localhost:3000/client

### Get Client by ID
GET http://localhost:3000/client/2c7f2e7b-4862-4762-a09f-d9873a106ced

### Update Client
PATCH http://localhost:3000/client/9292b61d-fc9c-432b-be2d-e3433e2fcacd
Content-Type: application/json

{
    "name": "Glory Mary_UwU",
    "email": "GloryMary@gmail.com",
    "password": "Beautiful123"
}

### Delete Client
DELETE http://localhost:3000/client/2c7f2e7b-4862-4762-a09f-d9873a106ced

### Create Employee
POST http://localhost:3000/employee
Content-Type: application/json

{
    "name": "RandomGuy",
    "email": "RandomGuy@gmail.com",
    "password": "RandomPassword123!",
    "CPF": "222.333.444-55",
    "phone": "(22) 98765-4321"
}



### Create Customer Service
POST http://localhost:3000/customer-service
Content-Type: application/json

{
    "idClient": "a54efa1e-482a-4697-bb66-84812f8d5a83",
    "idEmployee": "560cc6fa-7bf0-46da-89e0-1805c28f3e7f",
    "Date": "2022-01-01",
    "TotalValue": 100
}

### Get All Customer Services
GET http://localhost:3000/customer-service