### Create Client
POST http://localhost:3000/client
Content-Type: application/json

{
    "name": "Dulcineia",
    "email": "UmbrellaKindred@gmail.com",
    "password": "FuckSancho123!"
}

### Get All Clients
GET http://localhost:3000/client

### Get Client by ID
GET http://localhost:3000/client/2c7f2e7b-4862-4762-a09f-d9873a106ced

### Update Client
PATCH http://localhost:3000/client/9292b61d-fc9c-432b-be2d-e3433e2fcacd
Content-Type: application/json

{
    "name": "Glory Mary_UwU",
    "email": "GloryMary@gmail.com",
    "password": "Beautiful123"
}

### Delete Client
DELETE http://localhost:3000/client/2c7f2e7b-4862-4762-a09f-d9873a106ced

### Create Employee
POST http://localhost:3000/employee
Content-Type: application/json

{
    "name": "Jenifer",
    "email": "jenifer@studio.com",
    "password": "Password123!",
    "CPF": "123.456.789-00",
    "phone": "(13) 99999-9999",
    "commissionPercentage": 50,
    "skills": [
      "bc370a1a-7297-4e86-b099-86d1fe5b4894",
      "ac3c0360-a3fc-4a73-a458-6782883b7234",
      "dc9e4cfc-1d11-45a1-ae1f-b78af5ab31eb"
    ],
    "schedules": [
      { "dayOfWeek": 2, "startTime": "09:00", "endTime": "11:00" },
      { "dayOfWeek": 2, "startTime": "13:00", "endTime": "18:00" },
      { "dayOfWeek": 3, "startTime": "09:00", "endTime": "11:00" },
      { "dayOfWeek": 3, "startTime": "13:00", "endTime": "18:00" },
      { "dayOfWeek": 4, "startTime": "09:00", "endTime": "11:00" },
      { "dayOfWeek": 4, "startTime": "13:00", "endTime": "18:00" },
      { "dayOfWeek": 5, "startTime": "09:00", "endTime": "11:00" },
      { "dayOfWeek": 5, "startTime": "13:00", "endTime": "18:00" },
      { "dayOfWeek": 6, "startTime": "09:00", "endTime": "11:00" },
      { "dayOfWeek": 6, "startTime": "13:00", "endTime": "18:00" }
    ]
}


### Create Customer Service
POST http://localhost:3000/customer-service
Content-Type: application/json

{
    "idClient": "18bbeb01-be12-4ae9-9984-f56c3885f606",
    "employeeId": "b557d13c-108f-40d6-acf1-6257cc9bbe9c",
    "Date": "2026-04-21T09:00:00-03:00",
    "services": [
        {
            "serviceId": "bc370a1a-7297-4e86-b099-86d1fe5b4894",
            "customPrice": 50
        },
        {
            "serviceId": "ac3c0360-a3fc-4a73-a458-6782883b7234"
        }
    ]
}
### Create Customer Service
POST http://localhost:3000/customer-service
Content-Type: application/json

{
    "idClient": "18bbeb01-be12-4ae9-9984-f56c3885f606",
    "employeeId": "b557d13c-108f-40d6-acf1-6257cc9bbe9c",
    "Date": "2026-04-21T09:30:00-03:00",
    "services": [
        {
            "serviceId": "2a467d8e-5996-4be4-a405-2209f5f0a145"
        }
    ]
}

### Get All Customer Services
GET http://localhost:3000/customer-service

### Create Service
POST http://localhost:3000/services
Content-Type: application/json

{
    "name": "Corte",
    "price": 50.00,
    "estimatedDuration": 30
}

### Get All Services
GET http://localhost:3000/services

###get all employees
GET http://localhost:3000/employee

### Delete Service
DELETE http://localhost:3000/services/61996bff-b108-45d5-b485-c78c625a15f3