### Create Employee
@baseUrl = http://localhost:3000
@ManagerToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFuZHJlYWNhenVsYUBnbWFpbC5jb20iLCJzdWIiOiIzYThiYTAzMS1lMTFhLTQ2N2YtYWYwMS04OTFkZWM3MjBiMmMiLCJyb2xlIjoiTUFOQUdFUiIsImlhdCI6MTc4MDkzMzM2MiwiZXhwIjoxNzgwOTYyMTYyfQ.aRMAsjnWTlxZbDcNaUqv0Ph2k7rtF6rsiejQHYNvobI
@EscovaId = 6ae95d08-3d92-4f20-b5e0-078847d1324e
@TinturaId = 1528b65b-d993-4168-b743-3351bc72650b
@CorteId = 15e87e82-d80a-4792-92eb-98552438d38a
@PenteadoId = 108cddce-3b8f-45db-affc-416c35532f45
@MechasId = a729b724-a4ae-44ab-8da2-ccd3b6b9124b
@GlossId = 7779363b-1fa0-4e2e-9023-25bed9d8bdc2
@MaquiagemId = 718c9fae-3612-4739-9883-0d885d0200ea
@managerId = 3a8ba031-e11a-467f-af01-891dec720b2c

### Create Employee
POST {{baseUrl}}/employee
Content-Type: application/json
Authorization: Bearer {{ManagerToken}}

{
    "name": "Gilmara (Cabelereira)",
    "email": "gilmara@studio.com",
    "password": "Password123!",
    "CPF": "111.222.333-44",
    "phone": "(11) 98765-4321",
    "commissionPercentage": 40,
    "skills": [
      "{{EscovaId}}",
      "{{TinturaId}}",
      "{{CorteId}}",
      "{{PenteadoId}}"
    ],
    "schedules": [
      { "dayOfWeek": 2, "startTime": "13:00", "endTime": "18:00" },
      { "dayOfWeek": 3, "startTime": "13:00", "endTime": "18:00" },
      { "dayOfWeek": 4, "startTime": "13:00", "endTime": "18:00" },
      { "dayOfWeek": 5, "startTime": "09:00", "endTime": "11:00" },
      { "dayOfWeek": 5, "startTime": "13:00", "endTime": "18:00" },
      { "dayOfWeek": 6, "startTime": "09:00", "endTime": "11:00" },
      { "dayOfWeek": 6, "startTime": "13:00", "endTime": "18:00" }
    ]
}

### GET All Services
GET {{baseUrl}}/services
Authorization: Bearer {{ManagerToken}}

### GET All Employees
GET {{baseUrl}}/employee
Authorization: Bearer {{ManagerToken}}

### GET All Clients
GET {{baseUrl}}/client
Authorization: Bearer {{ManagerToken}}

### GET All CustomerService
GET {{baseUrl}}/customer-service
Authorization: Bearer {{ManagerToken}}


### Create Service
POST {{baseUrl}}/services
Content-Type: application/json
Authorization: Bearer {{ManagerToken}}

{
    "name": "Penteado",
    "price": 150.00,
    "estimatedDuration": 15
}

### Update Employee
PATCH {{baseUrl}}/employee/{{managerId}}
Content-Type: application/json
Authorization: Bearer {{ManagerToken}}

{
    "name": "Andreia",
    "email": "andreacazula@gmail.com",
    "password": "Password123!",
    "CPF": "222.333.444-55",
    "phone": "(11) 97654-3210",
    "commissionPercentage": 50,
    "skills": [
      "{{MechasId}}",
      "{{MaquiagemId}}",
      "{{GlossId}}",
      "{{TinturaId}}",
      "{{EscovaId}}"
      
    ],
    "schedules": [
      { "dayOfWeek": 2, "startTime": "09:00", "endTime": "11:00" },
      { "dayOfWeek": 2, "startTime": "13:00", "endTime": "18:00" },
      { "dayOfWeek": 3, "startTime": "09:00", "endTime": "11:00" },
      { "dayOfWeek": 3, "startTime": "13:00", "endTime": "18:00" },
      { "dayOfWeek": 4, "startTime": "09:00", "endTime": "11:00" },
      { "dayOfWeek": 4, "startTime": "13:00", "endTime": "18:00" },
      { "dayOfWeek": 5, "startTime": "09:00", "endTime": "11:00" },
      { "dayOfWeek": 5, "startTime": "13:00", "endTime": "18:00" },
      { "dayOfWeek": 6, "startTime": "09:00", "endTime": "11:00" },
      { "dayOfWeek": 6, "startTime": "13:00", "endTime": "18:00" }

    ]
}


### Manager Login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "andreacazula@gmail.com",
    "password": "Password123!"
}

### Delete Employee
DELETE {{baseUrl}}/employee/{{managerId}}
Authorization: Bearer {{ManagerToken}}


### Create Client
POST {{baseUrl}}/client
Content-Type: application/json
Authorization: Bearer {{ManagerToken}}

{
    "name": "Cliente Teste",
    "password": "Password123!",
    "email": "cliente@gmail.com",
    "phone": "(11) 91234-5678"
}

### Update Client
PATCH {{baseUrl}}/client/c91b2ded-eee1-488f-96f7-bea87e81b1c2
Content-Type: application/json
Authorization: Bearer {{ManagerToken}}

{
    "name": "Cliente Teste",
    "password": "Password123!",
    "phone": "(11) 91234-5678",
    "birthDate": "1990-05-25T00:00:00Z"
}

### Verify Client Email
POST {{baseUrl}}/client/verify
Content-Type: application/json

{   "email" : "cliente@gmail.com",
    "code": "967210"
}