### Create Employee
@baseUrl = http://localhost:3000
@ManagerToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZpY3Rvcmh1Z29Ac3R1ZGlvYS5jb20iLCJzdWIiOiI4ZWMzYWY5Ny01M2RkLTRhNzMtYjVhZC05NWFjNjAwMjRjOTQiLCJyb2xlIjoiTUFOQUdFUiIsImlhdCI6MTc3ODUyNTM2NywiZXhwIjoxNzc4NTU0MTY3fQ.HsSJId7PDlcF3_tLtvypRNWMI_iLBxuda9ugUsiz7Oo
@EscovaId = ac3c0360-a3fc-4a73-a458-6782883b7234
@TinturaId = dc9e4cfc-1d11-45a1-ae1f-b78af5ab31eb
@CorteId = 2a467d8e-5996-4be4-a405-2209f5f0a145
@PenteadoId = fea27d3b-6b1a-4854-96bb-7e1e240eba0b
@MechasId = 25df9b74-e94e-45eb-a68b-02d98f4c4ceb
@GlossId = 06a83b68-0da5-4e9a-9d5e-1a6809ca9cd4
@MaquiagemId = 8f565e90-02a9-437d-8264-d5265a2c8c2e

### Create Employee
POST {{baseUrl}}/employee
Content-Type: application/json
Authorization: Bearer {{ManagerToken}}

{
    "name": "Gilmara (Cabelereira)",
    "email": "gilmara@studio.com",
    "password": "Password123!",
    "CPF": "111.222.333-44",
    "phone": "(11) 98765-4321",
    "commissionPercentage": 40,
    "role": "MANAGER",
    "skills": [
      "{{EscovaId}}",
      "{{TinturaId}}",
      "{{CorteId}}",
      "{{PenteadoId}}"
    ],
    "schedules": [
      { "dayOfWeek": 2, "startTime": "13:00", "endTime": "18:00" },
      { "dayOfWeek": 3, "startTime": "13:00", "endTime": "18:00" },
      { "dayOfWeek": 4, "startTime": "13:00", "endTime": "18:00" },
      { "dayOfWeek": 5, "startTime": "09:00", "endTime": "11:00" },
      { "dayOfWeek": 5, "startTime": "13:00", "endTime": "18:00" },
      { "dayOfWeek": 6, "startTime": "09:00", "endTime": "11:00" },
      { "dayOfWeek": 6, "startTime": "13:00", "endTime": "18:00" }
    ]
}

### GET All Services
GET {{baseUrl}}/services

### Create Service
POST {{baseUrl}}/services
Content-Type: application/json
Authorization: Bearer {{ManagerToken}}

{
    "name": "Mechas",
    "price": 150,
    "estimatedDuration": 10
}

### Create Employee
POST {{baseUrl}}/employee
Content-Type: application/json
Authorization: Bearer {{ManagerToken}}

{
    "name": "Andreia",
    "email": "andreacazula@gmail.com",
    "password": "Password123!",
    "CPF": "222.333.444-55",
    "phone": "(11) 97654-3210",
    "commissionPercentage": 50,
    "role": "MANAGER",
    "skills": [
      "{{MechasId}}",
      "{{MaquiagemId}}",
      "{{GlossId}}",
      "{{TinturaId}}",
      "{{EscovaId}}"
      
    ],
    "schedules": [
      { "dayOfWeek": 2, "startTime": "09:00", "endTime": "11:00" },
      { "dayOfWeek": 2, "startTime": "13:00", "endTime": "18:00" },
      { "dayOfWeek": 3, "startTime": "09:00", "endTime": "11:00" },
      { "dayOfWeek": 3, "startTime": "13:00", "endTime": "18:00" },
      { "dayOfWeek": 4, "startTime": "09:00", "endTime": "11:00" },
      { "dayOfWeek": 4, "startTime": "13:00", "endTime": "18:00" },
      { "dayOfWeek": 5, "startTime": "09:00", "endTime": "11:00" },
      { "dayOfWeek": 5, "startTime": "13:00", "endTime": "18:00" },
      { "dayOfWeek": 6, "startTime": "09:00", "endTime": "11:00" },
      { "dayOfWeek": 6, "startTime": "13:00", "endTime": "18:00" }

    ]
}
