### Create Employee
@baseUrl = http://localhost:3000
@ManagerToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFuZHJlYWNhenVsYUBnbWFpbC5jb20iLCJzdWIiOiI0ZjM3OWQzYi0yNzgzLTRjMDAtYTVlZC0zMjcyYWUxZTgxMWYiLCJyb2xlIjoiTUFOQUdFUiIsImlhdCI6MTc4MTExNDQ4MSwiZXhwIjoxNzgxMTQzMjgxfQ.i3VKuu17Qnt32gvDwCQE4rXTW_Dbw-DTL96iRzl8DO0
@ManagerId = 4f379d3b-2783-4c00-a5ed-3272ae1e811f
@EscovaId = d9bfcdb5-f754-4219-a240-473bed8fd3e5
@TinturaId = f3134f34-9d91-4f90-b941-202fbe7eaca1
@CorteId = 15e87e82-d80a-4792-92eb-98552438d38a
@PenteadoId = 108cddce-3b8f-45db-affc-416c35532f45
@MechasId = e39b2972-3187-4dd7-8ed1-e2ae1918f013
@GlossId = ff29eca4-5e77-4a26-b1f6-14f54d705e6c
@MaquiagemId = d50640ae-cfb1-474b-9d71-15c2d6c7ee77
@ProgressivaId = 15a2b283-0edb-4f40-b3e0-0220d8d3fd7d

### Create Employee
POST {{baseUrl}}/employee
Content-Type: application/json
Authorization: Bearer {{ManagerToken}}

{
    "name": "Gilmara (Cabelereira)",
    "email": "gilmara@studio.com",
    "password": "Password123!",
    "CPF": "111.222.333-44",
    "phone": "(11) 98765-4321",
    "commissionPercentage": 40,
    "skills": [
      "{{EscovaId}}",
      "{{TinturaId}}",
      "{{CorteId}}",
      "{{PenteadoId}}"
    ],
    "schedules": [
      { "dayOfWeek": 2, "startTime": "13:00", "endTime": "18:00" },
      { "dayOfWeek": 3, "startTime": "13:00", "endTime": "18:00" },
      { "dayOfWeek": 4, "startTime": "13:00", "endTime": "18:00" },
      { "dayOfWeek": 5, "startTime": "09:00", "endTime": "11:00" },
      { "dayOfWeek": 5, "startTime": "13:00", "endTime": "18:00" },
      { "dayOfWeek": 6, "startTime": "09:00", "endTime": "11:00" },
      { "dayOfWeek": 6, "startTime": "13:00", "endTime": "18:00" }
    ]
}

### GET All Services
GET {{baseUrl}}/services
Authorization: Bearer {{ManagerToken}}

### GET All Employees
GET {{baseUrl}}/employee
Authorization: Bearer {{ManagerToken}}

### GET All Clients
GET {{baseUrl}}/client
Authorization: Bearer {{ManagerToken}}

### GET All CustomerService
GET {{baseUrl}}/customer-service
Authorization: Bearer {{ManagerToken}}


### Create Service
POST {{baseUrl}}/services
Content-Type: application/json
Authorization: Bearer {{ManagerToken}}

{
    "name": "Penteado",
    "price": 150.00,
    "estimatedDuration": 15
}

### Update Employee
PATCH {{baseUrl}}/employee/{{ManagerId}}
Content-Type: application/json
Authorization: Bearer {{ManagerToken}}

{
    "name": "Andreia",
    "email": "andreacazula@gmail.com",
    "password": "Password123!",
    "CPF": "222.333.444-55",
    "phone": "(11) 97654-3210",
    "commissionPercentage": 50,
    "skills": [
      "{{MechasId}}",
      "{{MaquiagemId}}",
      "{{GlossId}}",
      "{{TinturaId}}",
      "{{EscovaId}}"
      
    ],
    "schedules": [
      { "dayOfWeek": 2, "startTime": "09:00", "endTime": "11:00" },
      { "dayOfWeek": 2, "startTime": "13:00", "endTime": "18:00" },
      { "dayOfWeek": 3, "startTime": "09:00", "endTime": "11:00" },
      { "dayOfWeek": 3, "startTime": "13:00", "endTime": "18:00" },
      { "dayOfWeek": 4, "startTime": "09:00", "endTime": "11:00" },
      { "dayOfWeek": 4, "startTime": "13:00", "endTime": "18:00" },
      { "dayOfWeek": 5, "startTime": "09:00", "endTime": "11:00" },
      { "dayOfWeek": 5, "startTime": "13:00", "endTime": "18:00" },
      { "dayOfWeek": 6, "startTime": "09:00", "endTime": "11:00" },
      { "dayOfWeek": 6, "startTime": "13:00", "endTime": "18:00" }

    ]
}
### Create Employee Jenifer
POST http://localhost:3000/employee
Content-Type: application/json
Authorization: Bearer {{ManagerToken}}

{
    "name": "Jenifer",
    "email": "jenifer@studio.com",
    "password": "Password123!",
    "CPF": "123.456.789-00",
    "phone": "(13) 99999-9999",
    "commissionPercentage": 50,
    "skills": [
      "{{ProgressivaId}}",
      "{{EscovaId}}",
      "{{TinturaId}}"
    ],
    "schedules": [
      { "dayOfWeek": 2, "startTime": "09:00", "endTime": "11:00" },
      { "dayOfWeek": 2, "startTime": "13:00", "endTime": "18:00" },
      { "dayOfWeek": 3, "startTime": "09:00", "endTime": "11:00" },
      { "dayOfWeek": 3, "startTime": "13:00", "endTime": "18:00" },
      { "dayOfWeek": 4, "startTime": "09:00", "endTime": "11:00" },
      { "dayOfWeek": 4, "startTime": "13:00", "endTime": "18:00" },
      { "dayOfWeek": 5, "startTime": "09:00", "endTime": "11:00" },
      { "dayOfWeek": 5, "startTime": "13:00", "endTime": "18:00" },
      { "dayOfWeek": 6, "startTime": "09:00", "endTime": "11:00" },
      { "dayOfWeek": 6, "startTime": "13:00", "endTime": "18:00" }
    ]
}


### Manager Login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "andreacazula@gmail.com",
    "password": "Password123!"
}

### Delete Employee
DELETE {{baseUrl}}/employee/{{ManagerId}}
Authorization: Bearer {{ManagerToken}}


### Create Client
POST {{baseUrl}}/client
Content-Type: application/json
Authorization: Bearer {{ManagerToken}}

{
    "name": "Cliente Teste",
    "password": "Password123!",
    "email": "cliente@gmail.com",
    "phone": "(11) 91234-5678"
}

### Update Client
PATCH {{baseUrl}}/client/c91b2ded-eee1-488f-96f7-bea87e81b1c2
Content-Type: application/json
Authorization: Bearer {{ManagerToken}}

{
    "name": "Cliente Teste",
    "password": "Password123!",
    "phone": "(11) 91234-5678",
    "birthDate": "1990-05-25T00:00:00Z"
}

### Verify Client Email
POST {{baseUrl}}/client/verify
Content-Type: application/json

{   "email" : "cliente@gmail.com",
    "code": "967210"
}

### Delete Employee 

DELETE {{baseUrl}}/employee/dd89b677-8f07-450b-bef5-bb3c0ca56676
Authorization: Bearer {{ManagerToken}}
